
const TECH_TERMS=["oxygen","pressure","valve","reducer","absorber","ecu","battery","mask","cylinder","drain","relief","warning","alarm","hose","bag","diaphragm","belt","harness","disinfectant","temperature","ice","cooler","flow","bypass","sensor","epdm","o-ring","bayonet","sieve","spring","filter","cartridge","rfid","visor","strap","lever","cover","gauge","indicator","percent","purity","burst","disc","minimum","pre-flush"];
const SYNONYMS={oxygen:["O2","medical oxygen","compressed oxygen","breathing oxygen"],pressure:["gauge pressure","line pressure","system pressure","positive pressure"],valve:["flow valve","control valve","safety valve","check valve"],reducer:["regulator","pressure reducer","first stage","reducing valve"],absorber:["CO₂ canister","soda lime pack","scrubber","cartridge"],ecu:["monitor unit","control unit","electronic module","handset"],battery:["cell pack","primary cell","power cell","lithium cell"],mask:["facepiece","full face mask","respirator mask","visor mask"],cylinder:["tank","bottle","pressure vessel","O2 bottle"],drain:["purge","bleed","drainage","empty"],relief:["overpressure","safety","pressure release","pressure relief"],warning:["alert","caution","notice","alarm cue"],alarm:["buzzer","audible alert","alarm tone","signal"],hose:["tube","line","breathing hose","air line"],bag:["reservoir bag","breathing bag","bellows","sack"],diaphragm:["membrane","voice disc","speech membrane","diaphragm disc"],belt:["strap","waist strap","hip belt","belting"],harness:["shoulder straps","carrier","suspension","rigging"],disinfectant:["sanitizer","germicide","approved disinfectant","cleanser"],temperature:["heat level","air temperature","temp","°C/°F"],ice:["cold packs","ice packs","PCM packs","cooler packs"],cooler:["ice cooler","heat exchanger","cold unit","cooling insert"],flow:["throughput","gas flow","flow rate","delivery"],bypass:["manual bypass","emergency flow","override","bypass valve"],sensor:["transducer","detector","probe","sensor unit"],"o-ring":["seal ring","elastomer ring","gasket","O-ring"],bayonet:["bayonet ring","bayonet fitting","locking ring","twist lock"]};
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function isNumericToken(t){return /^(\d+(?:[.,]\d+)?)(?:\s*(?:%|psi|mbar|bar|L\/min|kg|lbs|°C|°F))?$/.test(t)}
function selectTechnicalNoun(text){const lower=text.toLowerCase();const cand=[];TECH_TERMS.forEach(t=>{if(lower.includes(t))cand.push(t)});const unit=text.match(/\b\d+(?:[.,]\d+)?\s*(?:psi|mbar|bar|L\/min|kg|lbs|°C|°F)\b/);if(unit)cand.push(unit[0]);if(cand.length)return pick(cand);const words=text.match(/\b[A-Za-z][A-Za-z\-]{2,}\b/g)||[];return words.length?pick(words):null}
function makeNearNumericOptions(orig){const m=orig.match(/(\d+(?:[.,]\d+)?)(?:\s*(psi|mbar|bar|L\/min|kg|lbs|°C|°F))?/);if(!m)return null;const base=parseFloat(m[1].replace(',','.'));const unit=m[2]||'';const deltas=[0,-.1,.1,-.05,.05,-.15,.15];const set=new Set();while(set.size<4){const d=pick(deltas);let v=base*(1+d);if(base>=1000)v=Math.round(v/10)*10;else if(base>=100)v=Math.round(v);else v=Math.round(v*10)/10;set.add(`${v}${unit?(' '+unit):''}`)}if(!set.has(orig)){const arr=[...set];arr[0]=orig;return shuffle(arr)}return [...set]}
function makeSynonymOptions(target){const key=(target||'').toLowerCase().replace(/[^a-z]/g,'');let syn=[];for(const k in SYNONYMS){if(key.includes(k.replace(/[^a-z]/g,''))){syn=SYNONYMS[k];break}}if(!syn.length)syn=[target,'system '+target,target+' device',target+' unit'];const opts=[...new Set([target,...syn])].slice(0,4);while(opts.length<4)opts.push(target);return shuffle(opts)}
function buildStatementQuestions(n){const chosen=shuffle(STATEMENTS_FULL.slice()).slice(0,n);return chosen.map(t=>{const target=selectTechnicalNoun(t);const blank=target?t.replace(new RegExp(target.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'____'):t.replace(/(\b\w{3,}\b)/,'____');let options;if(target&&isNumericToken(target))options=makeNearNumericOptions(target);else options=makeSynonymOptions(target||'component');if(!options.includes(target))options[0]=target||'component';options=shuffle(options);return{type:'statement',text:blank,answer:target||'component',options}})}
function buildPartsQuestions(n){const assys=shuffle(ASSEMBLIES.slice()).slice(0,Math.min(n,ASSEMBLIES.length));return assys.map(assy=>{const item=pick(assy.items);const pool=assy.items.map(i=>i.name).filter(nm=>nm!==item.name);const options=shuffle([item.name,...shuffle(pool).slice(0,3)]);return{type:'parts',assembly:assy.title,askNum:item.num,answer:item.name,options}})}
function renderApp(){const c=document.getElementById('app');c.innerHTML='';const qs=[...buildStatementQuestions(10),...buildPartsQuestions(10)];let score=0;qs.forEach((q,i)=>{const card=document.createElement('div');card.className='card';const h=document.createElement('div');h.className='qhead';h.textContent=q.type==='statement'?`Q${i+1} · Fill the blank`:`Q${i+1} · ${q.assembly} · Part #${q.askNum}`;const p=document.createElement('div');p.className='prompt';p.innerHTML=q.type==='statement'?q.text:`Select the correct name for part <b>#${q.askNum}</b>`;const opts=document.createElement('div');opts.className='options';q.options.forEach(opt=>{const b=document.createElement('button');b.className='option';b.textContent=opt;b.addEventListener('click',()=>{if(card.dataset.answered)return;card.dataset.answered='1';[...opts.children].forEach(x=>x.disabled=true);if(opt===q.answer){b.classList.add('correct');score++}else{b.classList.add('incorrect');[...opts.children].forEach(x=>{if(x.textContent===q.answer)x.classList.add('correct')})}document.getElementById('score').textContent=`Score: ${score} / ${qs.length}`});opts.appendChild(b)});card.appendChild(h);card.appendChild(p);card.appendChild(opts);c.appendChild(card)})}
document.addEventListener('DOMContentLoaded',()=>{renderApp();let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;document.getElementById('install').style.display='inline-flex'});document.getElementById('btnInstall').addEventListener('click',async()=>{if(deferred){deferred.prompt();deferred=null}})});
